/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chris
 */
public class Base extends javax.swing.JFrame {

    /**
     * Creates new form Base
     */
    public Base() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Iconos = new javax.swing.JPanel();
        Boton0 = new javax.swing.JLabel();
        Boton1 = new javax.swing.JLabel();
        Boton2 = new javax.swing.JLabel();
        Boton3 = new javax.swing.JLabel();
        Boton4 = new javax.swing.JLabel();
        Boton5 = new javax.swing.JLabel();
        Boton6 = new javax.swing.JLabel();
        Boton7 = new javax.swing.JLabel();
        Boton8 = new javax.swing.JLabel();
        Boton9 = new javax.swing.JLabel();
        Boton10 = new javax.swing.JLabel();
        Boton11 = new javax.swing.JLabel();
        Boton12 = new javax.swing.JLabel();
        Boton13 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Iconos.setLayout(new java.awt.GridLayout(1, 14));

        Boton0.setText("jLabel3");
        Iconos.add(Boton0);

        Boton1.setText("jLabel4");
        Iconos.add(Boton1);

        Boton2.setText("jLabel7");
        Iconos.add(Boton2);

        Boton3.setText("jLabel8");
        Iconos.add(Boton3);

        Boton4.setText("jLabel10");
        Iconos.add(Boton4);

        Boton5.setText("jLabel14");
        Iconos.add(Boton5);

        Boton6.setText("jLabel12");
        Iconos.add(Boton6);

        Boton7.setText("jLabel13");
        Iconos.add(Boton7);

        Boton8.setText("jLabel11");
        Iconos.add(Boton8);

        Boton9.setText("jLabel9");
        Iconos.add(Boton9);

        Boton10.setText("jLabel6");
        Iconos.add(Boton10);

        Boton11.setText("jLabel5");
        Iconos.add(Boton11);

        Boton12.setText("jLabel2");
        Iconos.add(Boton12);

        Boton13.setText("jLabel1");
        Iconos.add(Boton13);

        jPanel1.add(Iconos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 1540, 130));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/FondoBase.png"))); // NOI18N
        Fondo.setText("jLabel1");
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Base().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Boton0;
    private javax.swing.JLabel Boton1;
    private javax.swing.JLabel Boton10;
    private javax.swing.JLabel Boton11;
    private javax.swing.JLabel Boton12;
    private javax.swing.JLabel Boton13;
    private javax.swing.JLabel Boton2;
    private javax.swing.JLabel Boton3;
    private javax.swing.JLabel Boton4;
    private javax.swing.JLabel Boton5;
    private javax.swing.JLabel Boton6;
    private javax.swing.JLabel Boton7;
    private javax.swing.JLabel Boton8;
    private javax.swing.JLabel Boton9;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel Iconos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
